name: CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    # Thiết lập môi trường để chạy (ví dụ: Ubuntu)
    runs-on: ubuntu-latest

    # Các bước sẽ chạy
    steps:
    # Bước 1: Checkout mã nguồn từ repository
    - uses: actions/checkout@v4

    

    # Bước 2: Đăng nhập vào Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # Bước 2.1: Cài đặt docker-compose
    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Bước 3: Build Docker image bằng docker-compose
    - name: Build the Docker image
      run: docker-compose build
    
      
    
     # Bước 4: Gắn thẻ (tag) cho Docker image
    - name: Tag the Docker image neo4j
      run: |
        docker tag demodevops-neo4j ${{ secrets.DOCKER_USERNAME }}/neo4j:latest

    - name: Push the Docker neo4j
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/neo4j:latest